spring:
    datasource:
        url: jdbc:mysql://bm4z2kxqtrlwdbqttmjx-mysql.services.clever-cloud.com:3306/bm4z2kxqtrlwdbqttmjx?useSSL=false&serverTimezone=UTC
        username: u6qmidhdlhh1u6nc
        password: LQKCvwZnLdCE4pflfgFO
        
        
security:
    jwt:
        secret: ghk45jgheFRACKrogho834go3h4g
        issuer: Main
        ttlMillis: 86400000
